source "https://rubygems.org"

gem "jekyll", "~> 4.0"
gem "jekyll-remote-theme"
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "jekyll-twitter-plugin"
gem "jekyll-seo-tag"
gem "jekyll-include-cache"
gem "jekyll-paginate"
gem "kramdown-parser-gfm"
